namespace AlplaPortal.Domain.Entities;

/// <summary>
/// Primary aggregate root for the Contracts module.
/// Represents a legal agreement with a supplier/counterparty.
/// Status lifecycle: DRAFT → [UNDER_REVIEW] → ACTIVE → SUSPENDED/EXPIRED/TERMINATED.
/// </summary>
public class Contract
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Auto-generated at draft creation: CTR-YYYY-NNNN</summary>
    public string ContractNumber { get; set; } = string.Empty;

    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }

    // Classification
    public int ContractTypeId { get; set; }
    public ContractType ContractType { get; set; } = null!;

    // Status lifecycle (string code — matches LeaveRecord pattern)
    public string StatusCode { get; set; } = "DRAFT";

    // Counterparty
    public int? SupplierId { get; set; }
    public Supplier? Supplier { get; set; }

    /// <summary>Free-text fallback when no Supplier record is matched.</summary>
    public string? CounterpartyName { get; set; }

    // Organizational scope
    public int DepartmentId { get; set; }
    public Department Department { get; set; } = null!;

    public int CompanyId { get; set; }
    public Company Company { get; set; } = null!;

    /// <summary>Null = company-wide contract (applies to all plants).</summary>
    public int? PlantId { get; set; }
    public Plant? Plant { get; set; }

    // Dates
    public DateTime? SignedAtUtc { get; set; }
    public DateTime EffectiveDateUtc { get; set; }
    public DateTime ExpirationDateUtc { get; set; }
    public DateTime? TerminatedAtUtc { get; set; }

    // Renewal
    public bool AutoRenew { get; set; }
    public int? RenewalNoticeDays { get; set; }

    // Financial
    public decimal? TotalContractValue { get; set; }
    public int? CurrencyId { get; set; }
    public Currency? Currency { get; set; }

    /// <summary>Legacy free-text payment conditions. Kept for backwards compatibility.</summary>
    public string? PaymentTerms { get; set; }

    // ── Payment Rule (structured — DEC-117) ──────────────────────────────────────────
    // These fields model the structured payment deadline rule for obligations of this contract.
    // They live alongside the free-text PaymentTerms field. All are nullable so existing contracts are safe.

    /// <summary>
    /// How the due date is derived for obligations of this contract.
    /// Codes: FIXED_DAYS_AFTER_REFERENCE | FIXED_DAY_OF_MONTH | NEXT_MONTH_FIXED_DAY |
    ///        ON_RECEIPT | ADVANCE_PAYMENT | MANUAL | CUSTOM_TEXT
    /// See ContractConstants.PaymentTermTypes for full specification and FIXED_DAY_OF_MONTH interpretation.
    /// </summary>
    public string? PaymentTermTypeCode { get; set; }

    /// <summary>
    /// The business event that provides the starting reference date for due date calculation.
    /// Only relevant when PaymentTermTypeCode requires a reference event.
    /// Codes: CONTRACT_SIGN_DATE | OBLIGATION_CREATION_DATE | INVOICE_RECEIVED_DATE | MANUAL_REFERENCE_DATE
    /// </summary>
    public string? ReferenceEventTypeCode { get; set; }

    /// <summary>Number of days added to the reference date. Used by FIXED_DAYS_AFTER_REFERENCE.</summary>
    public int? PaymentTermDays { get; set; }

    /// <summary>Fixed calendar day (1–28). Used by FIXED_DAY_OF_MONTH and NEXT_MONTH_FIXED_DAY.</summary>
    public int? PaymentFixedDay { get; set; }

    /// <summary>
    /// When true, users may manually override the system-calculated due date at obligation level.
    /// Override is tracked via DueDateSourceCode = MANUAL_OVERRIDE on the obligation.
    /// </summary>
    public bool AllowsManualDueDateOverride { get; set; }

    /// <summary>
    /// Number of days after the due date before a late penalty starts accruing.
    /// GraceDate = DueDate + GracePeriodDays. PenaltyStartDate = GraceDate + 1.
    /// If null or 0, the penalty starts the day after the due date.
    /// </summary>
    public int? GracePeriodDays { get; set; }

    // Late Penalty (tracking only — no monetary calculation in this phase)
    public bool HasLatePenalty { get; set; }
    /// <summary>PERCENTAGE | FIXED_AMOUNT. Only meaningful when HasLatePenalty = true.</summary>
    public string? LatePenaltyTypeCode { get; set; }
    public decimal? LatePenaltyValue { get; set; }

    // Late Interest (tracking only — no monetary calculation in this phase)
    public bool HasLateInterest { get; set; }
    /// <summary>PERCENTAGE | FIXED_AMOUNT. Only meaningful when HasLateInterest = true.</summary>
    public string? LateInterestTypeCode { get; set; }
    public decimal? LateInterestValue { get; set; }

    /// <summary>
    /// Human-readable summary of the payment rule.
    /// For structured term types: auto-generated by ContractDueDateCalculator.BuildPaymentRuleSummary().
    /// For CUSTOM_TEXT: manually authored by the user — clearly labeled in the UI.
    /// </summary>
    public string? PaymentRuleSummary { get; set; }
    public string? FinancialNotes { get; set; }
    public string? PenaltyNotes { get; set; }

    // Legal
    public string? GoverningLaw { get; set; }
    public string? TerminationClauses { get; set; }


    // OCR Tracking
    /// <summary>
    /// References ContractOcrExtractionRecord.Id (stored as string for backward compatibility).
    /// Updated to the latest extraction record ID each time OCR runs.
    /// </summary>
    public string? OcrExtractionBatchId { get; set; }

    /// <summary>True once the user has confirmed all OCR-staged fields (via POST .../ocr/{id}/confirm).</summary>
    public bool OcrValidatedByUser { get; set; }

    /// <summary>
    /// Mirrors the latest ContractOcrExtractionRecord.Status for efficient filtering.
    /// Valid values: null (no OCR run), "PENDING", "PROCESSING", "COMPLETED", "FAILED".
    /// </summary>
    public string? OcrStatus { get; set; }


    // ── Two-step approval participants (DEC-118) ─────────────────────────────────────
    // Auto-assigned when the contract is submitted for review via POST /{id}/submit-review.
    // Cleared when the contract is returned to DRAFT.

    /// <summary>
    /// User assigned as Technical Approver for Stage 1.
    /// Resolved from Department.ResponsibleUserId at submission time.
    /// Null until the contract enters UNDER_TECHNICAL_REVIEW.
    /// </summary>
    public Guid? TechnicalApproverId { get; set; }
    public User? TechnicalApprover { get; set; }

    /// <summary>
    /// User assigned as Final Approver for Stage 2.
    /// Resolved from Company.FinalApproverUserId at submission time.
    /// Null until the contract enters UNDER_TECHNICAL_REVIEW.
    /// </summary>
    public Guid? FinalApproverId { get; set; }
    public User? FinalApprover { get; set; }

    // Audit
    public DateTime CreatedAtUtc { get; set; }
    public Guid CreatedByUserId { get; set; }
    public User CreatedByUser { get; set; } = null!;

    public DateTime? UpdatedAtUtc { get; set; }
    public Guid? UpdatedByUserId { get; set; }

    // Navigation collections
    public ICollection<ContractDocument> Documents { get; set; } = new List<ContractDocument>();
    public ICollection<ContractHistory> Histories { get; set; } = new List<ContractHistory>();
    public ICollection<ContractPaymentObligation> PaymentObligations { get; set; } = new List<ContractPaymentObligation>();
    public ICollection<ContractAlert> Alerts { get; set; } = new List<ContractAlert>();
    public ICollection<Request> LinkedRequests { get; set; } = new List<Request>();
}
