import { useEffect, useState, useRef, useCallback, useMemo } from 'react';
import { api } from '../../lib/api';
import {
    RefreshCw, ChevronLeft, ChevronRight, Calendar, LayoutGrid, X,
    Clock, AlertTriangle, Moon, Filter, Search
} from 'lucide-react';
import './hr-attendance-calendar.css';

// ─── Types ───

type ViewMode = 'month' | 'week';

interface AttendanceEmployee {
    innuxEmployeeId: number;
    fullName: string;
    department: string;
    plantName: string | null;
    companyName: string | null;
}

interface AttendanceDaySummary {
    innuxEmployeeId: number;
    date: string;
    scheduleCode: string | null;
    scheduleDescription: string | null;
    scheduleSigla: string | null;
    isRestDay: boolean;
    isOvernightShift: boolean;
    scheduleStartTime: string | null;
    scheduleEndTime: string | null;
    firstEntry: string | null;
    firstExit: string | null;
    absenceMinutes: number;
    justifiedAbsenceMinutes: number;
    expectedMinutes: number;
    balanceMinutes: number;
    punchCount: number;
    isValidated: boolean;
    missedMandatoryPeriods: boolean;
    anomalyDescription: string | null;
    justification: string | null;
    attendanceStatus: string;
}

interface CalendarResponse {
    data: AttendanceDaySummary[];
    employees: AttendanceEmployee[];
    employeeCount: number;
    scopeType: string;
    startDate: string;
    endDate: string;
}

interface DayDetail {
    summary: AttendanceDaySummary;
    rawPunches: Array<{
        innuxEmployeeId: number;
        date: string;
        time: string;
        direction: string;
        directionLabel: string;
        terminalName: string | null;
        isAutoGenerated: boolean;
    }>;
    periods: Array<{
        startTime: string | null;
        endTime: string | null;
        workCode: string | null;
        workDescription: string | null;
        absenceCode: string | null;
        absenceDescription: string | null;
        isDispensed: boolean;
    }>;
    workPlanCode: string | null;
    workPlanDescription: string | null;
}

// ─── Date utilities ───

function getISOWeek(date: Date): number {
    const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
    d.setUTCDate(d.getUTCDate() + 4 - (d.getUTCDay() || 7));
    const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
    return Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
}

function addDays(date: Date, n: number): Date {
    const d = new Date(date);
    d.setDate(d.getDate() + n);
    return d;
}

function getMonday(date: Date): Date {
    const d = new Date(date);
    const day = d.getDay();
    const diff = d.getDate() - day + (day === 0 ? -6 : 1);
    d.setDate(diff);
    return d;
}

function isSameDay(a: Date, b: Date): boolean {
    return a.getDate() === b.getDate() &&
        a.getMonth() === b.getMonth() &&
        a.getFullYear() === b.getFullYear();
}

function isWeekendDay(date: Date): boolean {
    return date.getDay() === 0 || date.getDay() === 6;
}

function formatQueryDate(d: Date): string {
    return d.toISOString().split('T')[0];
}

function formatMinutes(m: number): string {
    if (m === 0) return '0m';
    const h = Math.floor(m / 60);
    const min = m % 60;
    if (h === 0) return `${min}m`;
    if (min === 0) return `${h}h`;
    return `${h}h ${min}m`;
}

// ─── Status helpers ───

const STATUS_CONFIG: Record<string, { label: string; cssClass: string }> = {
    Present: { label: 'Presente', cssClass: 'present' },
    Absent: { label: 'Ausente', cssClass: 'absent' },
    JustifiedAbsence: { label: 'Ausência Justificada', cssClass: 'justified' },
    DayOff: { label: 'Folga', cssClass: 'dayoff' },
    Anomaly: { label: 'Anomalia', cssClass: 'anomaly' },
    Unknown: { label: 'Desconhecido', cssClass: 'unknown' },
};

function getStatusConfig(status: string) {
    return STATUS_CONFIG[status] || STATUS_CONFIG.Unknown;
}

function renderStatusCell(status: string) {
    const cfg = getStatusConfig(status);
    switch (cfg.cssClass) {
        case 'present':
            return <div className={`att-status att-status--present`}><div className="att-status__dot" /></div>;
        case 'absent':
            return <div className={`att-status att-status--absent`}><div className="att-status__dot" /></div>;
        case 'justified':
            return <div className={`att-status att-status--justified`}><div className="att-status__icon">▲</div></div>;
        case 'dayoff':
            return <div className={`att-status att-status--dayoff`}><div className="att-status__icon">—</div></div>;
        case 'anomaly':
            return <div className={`att-status att-status--anomaly`}><div className="att-status__icon">!</div></div>;
        default:
            return <div className={`att-status att-status--unknown`}><div className="att-status__icon">?</div></div>;
    }
}

// ─── Component ───

export default function HRAttendanceCalendar() {
    const [calendarData, setCalendarData] = useState<CalendarResponse | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [viewMode, setViewMode] = useState<ViewMode>('month');
    const [currentDate, setCurrentDate] = useState(new Date());
    const [isScrolled, setIsScrolled] = useState(false);
    const [isScrolledY, setIsScrolledY] = useState(false);
    const [showScrollHint, setShowScrollHint] = useState(false);
    const [currentPage, setCurrentPage] = useState(1);
    const pageSize = 15;

    // Filter state
    const [filterPlant, setFilterPlant] = useState<string>('');
    const [filterDepartment, setFilterDepartment] = useState<string>('');
    const [filterCompany, setFilterCompany] = useState<string>('');
    const [filterStatus, setFilterStatus] = useState<string>('');
    const [searchQuery, setSearchQuery] = useState<string>('');

    // Detail drawer state
    const [drawerOpen, setDrawerOpen] = useState(false);
    const [drawerEmployee, setDrawerEmployee] = useState<AttendanceEmployee | null>(null);
    const [drawerDate, setDrawerDate] = useState<Date | null>(null);
    const [drawerDetail, setDrawerDetail] = useState<DayDetail | null>(null);
    const [drawerLoading, setDrawerLoading] = useState(false);
    const [drawerError, setDrawerError] = useState<string | null>(null);

    const scrollRef = useRef<HTMLDivElement>(null);
    const today = new Date();

    // ─── Date range ───

    const getDateRange = useCallback((): { from: Date; to: Date } => {
        if (viewMode === 'week') {
            const monday = getMonday(currentDate);
            return { from: monday, to: addDays(monday, 6) };
        }
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();
        return { from: new Date(year, month, 1), to: new Date(year, month + 1, 0) };
    }, [currentDate, viewMode]);

    const days = useMemo((): Date[] => {
        const { from, to } = getDateRange();
        const result: Date[] = [];
        const d = new Date(from);
        while (d <= to) {
            result.push(new Date(d));
            d.setDate(d.getDate() + 1);
        }
        return result;
    }, [getDateRange]);

    // ─── Data grouping (employee×date lookup) ───

    const attendanceLookup = useMemo(() => {
        if (!calendarData?.data) return new Map<string, AttendanceDaySummary>();
        const map = new Map<string, AttendanceDaySummary>();
        for (const row of calendarData.data) {
            const dateStr = row.date.split('T')[0];
            map.set(`${row.innuxEmployeeId}_${dateStr}`, row);
        }
        return map;
    }, [calendarData]);

    // ─── Data loading ───

    const loadCalendar = useCallback(() => {
        setLoading(true);
        setError(null);
        const { from, to } = getDateRange();
        api.hrAttendance
            .getCalendar({ startDate: formatQueryDate(from), endDate: formatQueryDate(to) })
            .then((res: CalendarResponse) => {
                setCalendarData(res);
                setCurrentPage(1); // Reset to first page on new data
                setLoading(false);
            })
            .catch((err: any) => {
                console.error('Attendance calendar error:', err);
                setError(err?.message || 'Falha ao carregar dados de presença.');
                setLoading(false);
            });
    }, [getDateRange]);

    useEffect(() => { loadCalendar(); }, [loadCalendar]);

    // ─── Scroll tracking ───

    useEffect(() => {
        const el = scrollRef.current;
        if (!el) return;
        const handleScroll = () => {
            setIsScrolled(el.scrollLeft > 2);
            setIsScrolledY(el.scrollTop > 2);
            setShowScrollHint(el.scrollWidth > el.clientWidth && (el.scrollLeft + el.clientWidth) < el.scrollWidth - 4);
        };
        handleScroll();
        el.addEventListener('scroll', handleScroll, { passive: true });
        const obs = new ResizeObserver(handleScroll);
        obs.observe(el);
        return () => { el.removeEventListener('scroll', handleScroll); obs.disconnect(); };
    }, [calendarData]);


    // ─── Navigation ───

    const navPrev = () => {
        if (viewMode === 'week') setCurrentDate(addDays(currentDate, -7));
        else setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
    };

    const navNext = () => {
        if (viewMode === 'week') setCurrentDate(addDays(currentDate, 7));
        else setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));
    };

    const navToday = () => setCurrentDate(new Date());

    // ─── Labels ───

    const getNavLabel = (): string => {
        if (viewMode === 'week') {
            const { from, to } = getDateRange();
            const fmtD = (d: Date) => d.toLocaleDateString('pt-AO', { day: 'numeric', month: 'short' });
            return `${fmtD(from)} – ${fmtD(to)} ${to.getFullYear()}`;
        }
        return currentDate.toLocaleString('pt-AO', { month: 'long', year: 'numeric' });
    };

    const getWeekBadge = (): string | null => {
        if (viewMode !== 'week') return null;
        return `Sem. ${getISOWeek(currentDate)}`;
    };

    const getScopeHeader = (): { title: string; subtitle: string } => {
        const scope = calendarData?.scopeType || 'self';
        if (scope === 'self') {
            return { title: 'Meu Registo de Presenças', subtitle: 'O seu registo individual de assiduidade.' };
        }
        if (scope === 'all') {
            return { title: 'Presenças da Equipa', subtitle: 'Visão completa — todos os funcionários.' };
        }
        if (scope === 'hr') {
            return { title: 'Presenças da Equipa', subtitle: 'Escopo R.H. — funcionários mapeados.' };
        }
        return { title: 'Presenças da Equipa', subtitle: 'Funcionários do seu departamento.' };
    };

    const getScopeDescription = (): string => {
        const scope = calendarData?.scopeType || 'self';
        switch (scope) {
            case 'all': return 'Visão completa — todos os funcionários.';
            case 'hr': return 'Escopo R.H.';
            case 'department': return 'Escopo departamental.';
            case 'self': return 'Visão pessoal.';
            default: return '';
        }
    };

    // ─── Cell interaction ───

    const handleCellClick = (employee: AttendanceEmployee, day: Date) => {
        setDrawerEmployee(employee);
        setDrawerDate(day);
        setDrawerDetail(null);
        setDrawerError(null);
        setDrawerOpen(true);
        setDrawerLoading(true);

        api.hrAttendance
            .getDayDetail(employee.innuxEmployeeId, formatQueryDate(day))
            .then((detail: DayDetail) => {
                setDrawerDetail(detail);
                setDrawerLoading(false);
            })
            .catch((err: any) => {
                if (err?.status === 404) {
                    setDrawerDetail(null);
                    setDrawerLoading(false);
                } else {
                    setDrawerError(err?.message || 'Falha ao carregar detalhe.');
                    setDrawerLoading(false);
                }
            });
    };

    const closeDrawer = () => {
        setDrawerOpen(false);
        setDrawerEmployee(null);
        setDrawerDate(null);
        setDrawerDetail(null);
    };

    const navigateDrawer = (direction: 'prev' | 'next') => {
        if (!drawerEmployee || !drawerDate) return;
        const currentIdx = days.findIndex(d => isSameDay(d, drawerDate));
        if (currentIdx < 0) return;
        const nextIdx = direction === 'prev' ? currentIdx - 1 : currentIdx + 1;
        if (nextIdx < 0 || nextIdx >= days.length) return;
        handleCellClick(drawerEmployee, days[nextIdx]);
    };

    const drawerDayIndex = drawerDate ? days.findIndex(d => isSameDay(d, drawerDate)) : -1;
    const canDrawerPrev = drawerDayIndex > 0;
    const canDrawerNext = drawerDayIndex >= 0 && drawerDayIndex < days.length - 1;

    // ─── Derived values ───

    const scope = getScopeHeader();
    const weekBadge = getWeekBadge();
    const dayColWidth = viewMode === 'week' ? 80 : 40;
    const allEmployees = calendarData?.employees || [];

    // Filter option lists (derived from loaded data)
    const filterOptions = useMemo(() => {
        const plants = new Set<string>();
        const departments = new Set<string>();
        const companies = new Set<string>();
        for (const emp of allEmployees) {
            if (emp.plantName) plants.add(emp.plantName);
            if (emp.department) departments.add(emp.department);
            if (emp.companyName) companies.add(emp.companyName);
        }
        // Collect unique statuses from attendance data
        const statuses = new Set<string>();
        if (calendarData?.data) {
            for (const row of calendarData.data) {
                if (row.attendanceStatus) statuses.add(row.attendanceStatus);
            }
        }
        // Sort statuses by their Portuguese labels
        const sortedStatuses = [...statuses].sort((a, b) => {
            const la = getStatusConfig(a).label;
            const lb = getStatusConfig(b).label;
            return la.localeCompare(lb, 'pt-AO');
        });
        return {
            plants: [...plants].sort((a, b) => a.localeCompare(b, 'pt-AO')),
            departments: [...departments].sort((a, b) => a.localeCompare(b, 'pt-AO')),
            companies: [...companies].sort((a, b) => a.localeCompare(b, 'pt-AO')),
            statuses: sortedStatuses,
        };
    }, [allEmployees, calendarData]);

    const hasActiveFilters = !!(filterPlant || filterDepartment || filterCompany || filterStatus || searchQuery.trim());

    // Filtered → sorted → paginated pipeline
    // Build a set of employee IDs that have at least one cell matching the selected status
    const employeesWithStatus = useMemo(() => {
        if (!filterStatus || !calendarData?.data) return null;
        const ids = new Set<number>();
        for (const row of calendarData.data) {
            if (row.attendanceStatus === filterStatus) ids.add(row.innuxEmployeeId);
        }
        return ids;
    }, [filterStatus, calendarData]);

    const totalEmployees = useMemo(() => {
        let list = allEmployees;
        if (filterPlant) list = list.filter(e => e.plantName === filterPlant);
        if (filterDepartment) list = list.filter(e => e.department === filterDepartment);
        if (filterCompany) list = list.filter(e => e.companyName === filterCompany);
        if (employeesWithStatus) list = list.filter(e => employeesWithStatus.has(e.innuxEmployeeId));
        if (searchQuery.trim()) {
            const q = searchQuery.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
            list = list.filter(e => {
                const name = e.fullName.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
                return name.includes(q);
            });
        }
        return [...list].sort((a, b) => a.fullName.localeCompare(b.fullName, 'pt-AO'));
    }, [allEmployees, filterPlant, filterDepartment, filterCompany, employeesWithStatus, searchQuery]);

    const totalPages = Math.ceil(totalEmployees.length / pageSize);
    const employees = useMemo(() => {
        const start = (currentPage - 1) * pageSize;
        return totalEmployees.slice(start, start + pageSize);
    }, [totalEmployees, currentPage]);

    const clearFilters = () => {
        setFilterPlant('');
        setFilterDepartment('');
        setFilterCompany('');
        setFilterStatus('');
        setSearchQuery('');
        setCurrentPage(1);
    };

    // ─── Render ───

    return (
        <div className="att-root">
            {/* Header */}
            <div className="att-header">
                <div>
                    <h2 className="att-header__title">{scope.title}</h2>
                    <p className="att-header__subtitle">{scope.subtitle}</p>
                </div>

                <div className="att-controls">
                    <div className="att-view-toggle">
                        <button
                            className={`att-view-toggle__btn ${viewMode === 'month' ? 'att-view-toggle__btn--active' : ''}`}
                            onClick={() => setViewMode('month')}
                        >
                            <Calendar size={14} /> Mês
                        </button>
                        <button
                            className={`att-view-toggle__btn ${viewMode === 'week' ? 'att-view-toggle__btn--active' : ''}`}
                            onClick={() => setViewMode('week')}
                        >
                            <LayoutGrid size={14} /> Semana
                        </button>
                    </div>

                    <div className="att-nav">
                        <button className="att-nav__btn" onClick={navPrev} title={viewMode === 'week' ? 'Semana anterior' : 'Mês anterior'}>
                            <ChevronLeft size={18} />
                        </button>
                        <span className="att-nav__label">
                            {getNavLabel()}
                            {weekBadge && <span className="att-week-badge">{weekBadge}</span>}
                        </span>
                        <button className="att-nav__btn" onClick={navNext} title={viewMode === 'week' ? 'Próxima semana' : 'Próximo mês'}>
                            <ChevronRight size={18} />
                        </button>
                    </div>
                    <button className="att-nav__today" onClick={navToday}>Hoje</button>

                    {totalPages > 1 && (
                        <div className="att-pagination">
                            <button 
                                className="att-pagination__btn" 
                                onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                                disabled={currentPage === 1}
                            >
                                <ChevronLeft size={16} />
                            </button>
                            <span className="att-pagination__info">
                                {currentPage} / {totalPages}
                            </span>
                            <button 
                                className="att-pagination__btn" 
                                onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                                disabled={currentPage === totalPages}
                            >
                                <ChevronRight size={16} />
                            </button>
                        </div>
                    )}
                </div>
            </div>

            {/* Filters */}
            <div className="att-filters">
                <div className="att-filters__icon"><Filter size={14} /></div>

                <div className="att-filters__search">
                    <Search size={14} className="att-filters__search-icon" />
                    <input
                        type="text"
                        className="att-filters__search-input"
                        placeholder="Pesquisar funcionário..."
                        value={searchQuery}
                        onChange={e => { setSearchQuery(e.target.value); setCurrentPage(1); }}
                    />
                </div>

                    {filterOptions.companies.length > 1 && (
                        <select
                            className="att-filters__select"
                            value={filterCompany}
                            onChange={e => { setFilterCompany(e.target.value); setCurrentPage(1); }}
                        >
                            <option value="">Todas Empresas</option>
                            {filterOptions.companies.map(c => <option key={c} value={c}>{c}</option>)}
                        </select>
                    )}

                    {filterOptions.plants.length > 1 && (
                        <select
                            className="att-filters__select"
                            value={filterPlant}
                            onChange={e => { setFilterPlant(e.target.value); setCurrentPage(1); }}
                        >
                            <option value="">Todas Plantas</option>
                            {filterOptions.plants.map(p => <option key={p} value={p}>{p}</option>)}
                        </select>
                    )}

                    {filterOptions.departments.length > 1 && (
                        <select
                            className="att-filters__select"
                            value={filterDepartment}
                            onChange={e => { setFilterDepartment(e.target.value); setCurrentPage(1); }}
                        >
                            <option value="">Todos Departamentos</option>
                            {filterOptions.departments.map(d => <option key={d} value={d}>{d}</option>)}
                        </select>
                    )}

                    {filterOptions.statuses.length > 1 && (
                        <select
                            className="att-filters__select"
                            value={filterStatus}
                            onChange={e => { setFilterStatus(e.target.value); setCurrentPage(1); }}
                        >
                            <option value="">Todos Status</option>
                            {filterOptions.statuses.map(s => <option key={s} value={s}>{getStatusConfig(s).label}</option>)}
                        </select>
                    )}

                    {hasActiveFilters && (
                        <button className="att-filters__clear" onClick={clearFilters} title="Limpar filtros">
                            <X size={14} /> Limpar
                        </button>
                    )}
                </div>

            {/* Grid */}
            {loading ? (
                <div className="att-loading">
                    <RefreshCw size={24} color="#94a3b8" className="att-loading__icon" />
                    <div className="att-loading__text">A carregar presenças...</div>
                </div>
            ) : error ? (
                <div className="att-error">
                    <div className="att-error__text">{error}</div>
                    <button className="att-error__retry" onClick={loadCalendar}>Tentar novamente</button>
                </div>
            ) : employees.length > 0 ? (
                <div className="att-grid-shell">
                    <div
                        ref={scrollRef}
                        className={`att-scroll-viewport${isScrolled ? ' att-scroll-viewport--scrolled' : ''}${isScrolledY ? ' att-scroll-viewport--scrolled-y' : ''}`}
                    >
                        <table className="att-table" style={{ minWidth: `${280 + days.length * dayColWidth}px` }}>
                            <colgroup>
                                <col style={{ width: '280px' }} />
                                {days.map(d => (
                                    <col key={d.toISOString()} style={{ width: `${dayColWidth}px` }} />
                                ))}
                            </colgroup>
                            <thead>
                                <tr>
                                    <th className="att-frozen-col">
                                        <div className="att-frozen-col__header">
                                            <span className="att-frozen-col__label">Funcionário</span>
                                            {totalEmployees.length > 0 && (
                                                <span className="att-frozen-col__count">({totalEmployees.length})</span>
                                            )}
                                        </div>
                                    </th>
                                    {days.map(d => {
                                        const todayClass = isSameDay(d, today) ? ' att-day-header--today' : '';
                                        const weekendClass = isWeekendDay(d) ? ' att-day-header--weekend' : '';
                                        return (
                                            <th key={d.toISOString()} className={`att-day-header${weekendClass}${todayClass}`}>
                                                <span className="att-day-header__weekday">
                                                    {d.toLocaleString('pt-AO', { weekday: 'narrow' })}
                                                </span>
                                                <span className="att-day-header__number">{d.getDate()}</span>
                                            </th>
                                        );
                                    })}
                                </tr>
                            </thead>
                            <tbody>
                                {employees.map(emp => (
                                    <tr key={emp.innuxEmployeeId}>
                                        <td className="att-frozen-col">
                                            <div className="att-employee">
                                                <span className="att-employee__name" title={emp.fullName}>{emp.fullName}</span>
                                                <span className="att-employee__dept">{emp.department}</span>
                                            </div>
                                        </td>
                                        {days.map((d, dayIdx) => {
                                            const dateKey = formatQueryDate(d);
                                            const record = attendanceLookup.get(`${emp.innuxEmployeeId}_${dateKey}`);
                                            const weekend = isWeekendDay(d);
                                            const isCurrentDay = isSameDay(d, today);
                                            const todayBorder = isCurrentDay ? ' att-day-cell--today-border' : '';
                                            const restDay = record?.isRestDay || false;

                                            // Overnight connector: start marker on this day
                                            const isOvernightStart = !!(record?.isOvernightShift && !record.isRestDay);
                                            // Overnight connector: end marker (previous day was overnight)
                                            const prevDateKey = dayIdx > 0 ? formatQueryDate(days[dayIdx - 1]) : null;
                                            const prevRecord = prevDateKey ? attendanceLookup.get(`${emp.innuxEmployeeId}_${prevDateKey}`) : null;
                                            const isOvernightEnd = !!(prevRecord?.isOvernightShift && !prevRecord.isRestDay);

                                            let cellClass = 'att-day-cell';
                                            if (weekend) cellClass += ' att-day-cell--weekend';
                                            if (isCurrentDay && !record) cellClass += ' att-day-cell--today';
                                            cellClass += todayBorder;
                                            if (restDay) cellClass += ' att-day-cell--rest';
                                            if (isOvernightStart) cellClass += ' att-day-cell--overnight-start';
                                            if (isOvernightEnd) cellClass += ' att-day-cell--overnight-end';

                                            // Tooltip
                                            let cellTitle = record ? getStatusConfig(record.attendanceStatus).label : '';
                                            if (isOvernightStart && record?.scheduleStartTime && record?.scheduleEndTime) {
                                                cellTitle += ` | Turno noturno: ${record.scheduleStartTime} → ${record.scheduleEndTime} (+1 dia)`;
                                            }

                                            return (
                                                <td
                                                    key={d.toISOString()}
                                                    className={cellClass}
                                                    onClick={() => handleCellClick(emp, d)}
                                                    title={cellTitle}
                                                >
                                                    {isCurrentDay && <div className="att-today-indicator" />}
                                                    {record && renderStatusCell(record.attendanceStatus)}
                                                    {record?.scheduleSigla && (
                                                        <span className="att-cell-sigla">{record.scheduleSigla}</span>
                                                    )}
                                                </td>
                                            );
                                        })}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>

                    <div className={`att-scroll-hint ${showScrollHint ? 'att-scroll-hint--visible' : ''}`} />


                    {/* Legend */}
                    <div className="att-legend">
                        <div className="att-legend__item"><div className="att-legend__swatch att-legend__swatch--present" /><span className="att-legend__text">Presente</span></div>
                        <div className="att-legend__item"><div className="att-legend__swatch att-legend__swatch--absent" /><span className="att-legend__text">Ausente</span></div>
                        <div className="att-legend__item"><div className="att-legend__swatch att-legend__swatch--justified" /><span className="att-legend__text">Justificada</span></div>
                        <div className="att-legend__item"><div className="att-legend__swatch att-legend__swatch--dayoff" /><span className="att-legend__text">Folga</span></div>
                        <div className="att-legend__item"><div className="att-legend__swatch att-legend__swatch--anomaly" /><span className="att-legend__text">Anomalia</span></div>
                        <div className="att-legend__item"><div className="att-legend__swatch att-legend__swatch--overnight" /><span className="att-legend__text">Turno Noturno</span></div>
                        <span className="att-legend__scope">{getScopeDescription()}</span>
                    </div>
                </div>
            ) : (
                <div className="att-empty">
                    {calendarData?.scopeType === 'self'
                        ? 'Nenhum registo de presença encontrado para a sua conta.'
                        : 'Nenhum funcionário mapeado no seu escopo de hierarquia.'}
                </div>
            )}

            {/* Detail Drawer */}
            {drawerOpen && (
                <>
                    <div className="att-drawer-overlay" onClick={closeDrawer} />
                    <div className="att-drawer">
                        <div className="att-drawer__header">
                            <div style={{ flex: 1, minWidth: 0 }}>
                                <h3 className="att-drawer__title">
                                    {drawerEmployee?.fullName || 'Detalhe'}
                                </h3>
                                <div className="att-drawer__nav-row">
                                    <button
                                        className="att-drawer__nav-btn"
                                        onClick={() => navigateDrawer('prev')}
                                        disabled={!canDrawerPrev}
                                        title="Dia anterior"
                                    >
                                        <ChevronLeft size={16} />
                                    </button>
                                    <p className="att-drawer__subtitle">
                                        {drawerDate?.toLocaleDateString('pt-AO', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}
                                    </p>
                                    <button
                                        className="att-drawer__nav-btn"
                                        onClick={() => navigateDrawer('next')}
                                        disabled={!canDrawerNext}
                                        title="Dia seguinte"
                                    >
                                        <ChevronRight size={16} />
                                    </button>
                                </div>
                            </div>
                            <button className="att-drawer__close" onClick={closeDrawer}>
                                <X size={20} />
                            </button>
                        </div>

                        <div className="att-drawer__body">
                            {drawerLoading ? (
                                <div className="att-drawer__loading">
                                    <RefreshCw size={18} className="att-loading__icon" />
                                    <span>A carregar...</span>
                                </div>
                            ) : drawerError ? (
                                <div className="att-drawer__error">{drawerError}</div>
                            ) : drawerDetail ? (
                                <DrawerContent detail={drawerDetail} />
                            ) : (
                                <div className="att-detail-empty">
                                    Sem dados de presença para este dia.
                                </div>
                            )}
                        </div>
                    </div>
                </>
            )}
        </div>
    );
}

// ─── Drawer Content (sub-component) ───

function DrawerContent({ detail }: { detail: DayDetail }) {
    const { summary, rawPunches, periods } = detail;
    const cfg = getStatusConfig(summary.attendanceStatus);

    // Build overnight schedule label
    const overnightLabel = summary.isOvernightShift && summary.scheduleStartTime && summary.scheduleEndTime
        ? `${summary.scheduleStartTime} → ${summary.scheduleEndTime} (+1 dia)`
        : null;

    return (
        <>
            {/* Overnight badge */}
            {summary.isOvernightShift && !summary.isRestDay && (
                <div className="att-overnight-badge">
                    <Moon size={14} />
                    <span>Turno Noturno</span>
                    {overnightLabel && <span className="att-overnight-badge__time">{overnightLabel}</span>}
                </div>
            )}

            {/* Summary */}
            <div className="att-detail-section">
                <div className="att-detail-section__title">Resumo</div>
                <div className={`att-status-badge att-status-badge--${cfg.cssClass}`}>
                    {cfg.label}
                </div>
                <div className="att-summary-grid">
                    <SummaryItem label="Entrada" value={summary.firstEntry || '—'} />
                    <SummaryItem label="Saída" value={summary.firstExit || '—'} />
                    <SummaryItem label="Esperado" value={formatMinutes(summary.expectedMinutes)} />
                    <SummaryItem label="Ausência" value={summary.absenceMinutes > 0 ? formatMinutes(summary.absenceMinutes) : '—'} />
                    <SummaryItem label="Aus. Justificada" value={summary.justifiedAbsenceMinutes > 0 ? formatMinutes(summary.justifiedAbsenceMinutes) : '—'} />
                    <SummaryItem label="Saldo" value={formatMinutes(summary.balanceMinutes)} provisional />
                    <SummaryItem label="Marcações" value={String(summary.punchCount)} />
                    <SummaryItem label="Validado" value={summary.isValidated ? 'Sim' : 'Não'} />
                    {summary.scheduleDescription && (
                        <SummaryItem label="Horário" value={`${summary.scheduleDescription}${summary.scheduleSigla ? ` (${summary.scheduleSigla})` : ''}`} />
                    )}
                    {summary.isRestDay && (
                        <SummaryItem label="Tipo Dia" value="Dia de Descanso" />
                    )}
                    {summary.anomalyDescription && (
                        <SummaryItem label="Anomalia" value={summary.anomalyDescription} />
                    )}
                    {summary.justification && (
                        <SummaryItem label="Justificação" value={summary.justification} />
                    )}
                </div>
                {detail.workPlanDescription && (
                    <div className="att-summary-grid" style={{ marginTop: 8 }}>
                        <SummaryItem label="Plano de Trabalho" value={detail.workPlanDescription} />
                    </div>
                )}
            </div>

            {/* Periods */}
            <div className="att-detail-section">
                <div className="att-detail-section__title">Períodos</div>
                {periods.length > 0 ? (
                    periods.map((p, i) => (
                        <div key={i} className={`att-period ${p.isDispensed ? 'att-period--dispensed' : ''}`}>
                            <div className="att-period__time">
                                {p.startTime || '??:??'} — {p.endTime || '??:??'}
                            </div>
                            <div className="att-period__info">
                                {p.workCode && <span className="att-period__code">{p.workCode}</span>}
                                {p.workDescription && <span className="att-period__desc">{p.workDescription}</span>}
                                {p.absenceCode && <span className="att-period__code" style={{ color: '#d97706' }}>{p.absenceCode}</span>}
                                {p.absenceDescription && <span className="att-period__desc">{p.absenceDescription}</span>}
                                {p.isDispensed && <span className="att-period__desc" style={{ fontStyle: 'italic' }}>Dispensado</span>}
                            </div>
                        </div>
                    ))
                ) : (
                    <div className="att-detail-empty">Sem períodos registados.</div>
                )}
            </div>

            {/* Raw Punches */}
            <div className="att-detail-section">
                <div className="att-detail-section__title">
                    <span style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                        <Clock size={12} /> Marcações Brutas
                    </span>
                </div>
                {rawPunches.length > 0 ? (
                    <table className="att-punches-table">
                        <thead>
                            <tr>
                                <th>Hora</th>
                                <th>Direcção</th>
                                <th>Terminal</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {rawPunches.map((p, i) => (
                                <tr key={i}>
                                    <td style={{ fontWeight: 700 }}>{p.time}</td>
                                    <td>{p.directionLabel || p.direction}</td>
                                    <td>{p.terminalName || '—'}</td>
                                    <td>{p.isAutoGenerated && <span className="att-punch-auto">Auto</span>}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                ) : (
                    <div className="att-detail-empty">Sem marcações brutas.</div>
                )}
            </div>
        </>
    );
}

function SummaryItem({ label, value, provisional }: { label: string; value: string; provisional?: boolean }) {
    return (
        <div className="att-summary-item">
            <span className="att-summary-item__label">{label}</span>
            <span className={`att-summary-item__value ${provisional ? 'att-summary-item__value--provisional' : ''}`}>
                {value}
                {provisional && <AlertTriangle size={10} style={{ marginLeft: 4, verticalAlign: 'middle' }} />}
            </span>
        </div>
    );
}
