/**
 * HRAttendanceDiagnostics — Phase 4 Diagnostic Review UI
 *
 * Read-only diagnostic page for HR/Admin users to review attendance
 * discrepancies between Innux processed data and Portal raw-punch interpretation.
 *
 * ⚠️ This page does NOT modify any data in Innux or Primavera.
 * ⚠️ Access restricted to System Administrator and HR roles only.
 */
import { useState, useCallback, useEffect, useRef } from 'react';
import { api } from '../../lib/api';
import { useAuth } from '../../features/auth/AuthContext';
import { ROLES } from '../../constants/roles';
import { KPICard } from '../../components/ui/KPICard';
import {
    ShieldCheck, Search, Loader2, AlertTriangle, CheckCircle2,
    Info, X, Clock, CircleDot, Eye, AlertCircle,
    FileSearch, ChevronRight, HelpCircle, BookOpen
} from 'lucide-react';
import { ModernTooltip } from '../../components/ui/ModernTooltip';
import './hr-attendance-diagnostics.css';

// ─── Types ───

interface ComparisonResult {
    innuxEmployeeId: number;
    employeeName: string | null;
    date: string;
    innuxStatus: string;
    innuxFirstEntry: string | null;
    innuxLastExit: string | null;
    innuxWorkedMinutes: number;
    innuxWorkedMinutesSource: string;
    innuxWorkedMinutesEnriched: boolean;
    innuxExpectedMinutes: number;
    portalStatus: string;
    portalFirstEntry: string | null;
    portalLastExit: string | null;
    portalWorkedMinutes: number;
    portalExpectedMinutes: number;
    hasDiscrepancy: boolean;
    discrepancySeverity: string;
    discrepancyTypes: string[];
    discrepancyMessages: string[];
    recommendedReviewAction: string;
    confidenceLevel: string;
    portalWarnings: string[];
    scheduleResolutionSource: string;
}

interface RangeResult {
    startDate: string;
    endDate: string;
    totalEmployeeDays: number;
    discrepancyCount: number;
    highSeverityCount: number;
    mediumSeverityCount: number;
    lowSeverityCount: number;
    executionTimeMs: number;
    results: ComparisonResult[];
}

interface InterpretedPunch {
    punchTime: string;
    punchTimeFormatted: string;
    rawDirection: string | null;
    interpretedDirection: string;
    directionLabel: string;
    terminalName: string | null;
    terminalId: number | null;
    isAutoGenerated: boolean;
    interpretationRule: string;
    interpretationReason: string;
    confidence: string;
    isDuplicateCandidate: boolean;
    ignoredForCalculation: boolean;
    duplicateReason: string | null;
}

interface PunchPair {
    entry: InterpretedPunch | null;
    exit: InterpretedPunch | null;
    workedMinutes: number;
    pairType: string;
}

interface PunchInterpretation {
    innuxEmployeeId: number;
    date: string;
    resolvedSchedule: any;
    rawPunches: InterpretedPunch[];
    punchPairs: PunchPair[];
    interpretedFirstEntry: string | null;
    interpretedLastExit: string | null;
    totalWorkedMinutes: number;
    confidenceLevel: string;
    warnings: string[];
    appliedRules: string[];
}

// ─── Helpers ───

function formatDate(d: string) {
    const dt = new Date(d);
    return dt.toLocaleDateString('pt-AO', { day: '2-digit', month: '2-digit', year: 'numeric' });
}

function toIsoDate(d: Date) {
    return d.toISOString().split('T')[0];
}

function daysBetween(a: string, b: string) {
    return Math.ceil((new Date(b).getTime() - new Date(a).getTime()) / 86400000);
}

function defaultStartDate() {
    const d = new Date();
    d.setDate(d.getDate() - 6);
    return toIsoDate(d);
}

function severityLabel(s: string) {
    switch (s) {
        case 'High': return 'Alta';
        case 'Medium': return 'Média';
        case 'Low': return 'Baixa';
        default: return 'Nenhuma';
    }
}

function severityClass(s: string) {
    switch (s) {
        case 'High': return 'diag-severity--high';
        case 'Medium': return 'diag-severity--medium';
        case 'Low': return 'diag-severity--low';
        default: return 'diag-severity--none';
    }
}

function confidenceClass(c: string) {
    switch (c) {
        case 'High': return 'diag-confidence--high';
        case 'Medium': return 'diag-confidence--medium';
        case 'Low': return 'diag-confidence--low';
        default: return 'diag-confidence--none';
    }
}

function confidenceLabel(c: string) {
    switch (c) {
        case 'High': return 'Alta';
        case 'Medium': return 'Média';
        case 'Low': return 'Baixa';
        default: return '—';
    }
}

function statusLabel(s: string) {
    const map: Record<string, string> = {
        Present: 'Presente', Absent: 'Ausente', JustifiedAbsence: 'Ausência Justificada',
        Vacation: 'Férias', Holiday: 'Feriado', DayOff: 'Folga', Anomaly: 'Anomalia',
        NoPunches: 'Sem Picagens', Incomplete: 'Incompleto', PresentOnRestDay: 'Presente em Folga',
        PortalInterpreted: 'Portal-Interpretado', Unknown: 'Desconhecido'
    };
    return map[s] || s;
}

function msgClass(severity: string) {
    switch (severity) {
        case 'High': return 'msg-high';
        case 'Medium': return 'msg-medium';
        case 'Low': return 'msg-low';
        default: return 'msg-info';
    }
}

// ─── Component ───

export default function HRAttendanceDiagnostics() {
    const { user } = useAuth();

    // ─── Page-level role guard ───
    const hasAccess = user?.roles.some(r =>
        r === ROLES.SYSTEM_ADMINISTRATOR || r === ROLES.HR
    ) ?? false;

    if (!hasAccess) {
        return (
            <div style={{ padding: '60px 20px', textAlign: 'center', color: 'var(--color-text-muted)' }}>
                <AlertTriangle size={40} style={{ opacity: 0.3, marginBottom: 12 }} />
                <p style={{ fontSize: '1rem', fontWeight: 600 }}>Acesso restrito</p>
                <p style={{ fontSize: '0.85rem' }}>Esta página está disponível apenas para Administradores e utilizadores de RH.</p>
            </div>
        );
    }

    return <DiagnosticsContent />;
}

// ─── Employee Autocomplete Sub-Component ───

interface EmployeeOption {
    id: string;
    fullName: string;
    employeeCode: string;
    innuxEmployeeId: number;
    innuxDepartmentName: string | null;
}

function EmployeeAutocomplete({ value, onChange }: {
    value: EmployeeOption | null;
    onChange: (emp: EmployeeOption | null) => void;
}) {
    const [query, setQuery] = useState('');
    const [options, setOptions] = useState<EmployeeOption[]>([]);
    const [showDropdown, setShowDropdown] = useState(false);
    const [searching, setSearching] = useState(false);
    const [activeIndex, setActiveIndex] = useState(-1);
    const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
    const wrapperRef = useRef<HTMLDivElement>(null);
    const inputRef = useRef<HTMLInputElement>(null);

    // Debounced search
    useEffect(() => {
        if (value) return; // Don't search when an employee is already selected
        if (query.trim().length < 2) {
            setOptions([]);
            setShowDropdown(false);
            return;
        }
        setSearching(true);
        if (debounceRef.current) clearTimeout(debounceRef.current);
        debounceRef.current = setTimeout(async () => {
            try {
                const res = await api.hrLeave.getEmployees({ search: query.trim(), pageSize: 15 });
                const items: EmployeeOption[] = (res.items || []).filter((e: any) => e.innuxEmployeeId > 0);
                setOptions(items);
                setShowDropdown(true);
                setActiveIndex(-1);
            } catch {
                setOptions([]);
            } finally {
                setSearching(false);
            }
        }, 300);
        return () => { if (debounceRef.current) clearTimeout(debounceRef.current); };
    }, [query, value]);

    // Close dropdown on outside click
    useEffect(() => {
        const handler = (e: MouseEvent) => {
            if (wrapperRef.current && !wrapperRef.current.contains(e.target as Node)) {
                setShowDropdown(false);
            }
        };
        document.addEventListener('mousedown', handler);
        return () => document.removeEventListener('mousedown', handler);
    }, []);

    const selectEmployee = (emp: EmployeeOption) => {
        onChange(emp);
        setQuery('');
        setShowDropdown(false);
        setOptions([]);
    };

    const clearSelection = () => {
        onChange(null);
        setQuery('');
        setOptions([]);
        setShowDropdown(false);
        inputRef.current?.focus();
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (!showDropdown || options.length === 0) return;
        if (e.key === 'ArrowDown') {
            e.preventDefault();
            setActiveIndex(i => Math.min(i + 1, options.length - 1));
        } else if (e.key === 'ArrowUp') {
            e.preventDefault();
            setActiveIndex(i => Math.max(i - 1, 0));
        } else if (e.key === 'Enter' && activeIndex >= 0) {
            e.preventDefault();
            selectEmployee(options[activeIndex]);
        } else if (e.key === 'Escape') {
            setShowDropdown(false);
        }
    };

    return (
        <div className="diag-employee-autocomplete" ref={wrapperRef}>
            {value ? (
                <>
                    <input
                        type="text"
                        readOnly
                        value={`${value.fullName} (#${value.innuxEmployeeId})`}
                        style={{ cursor: 'default', fontWeight: 600 }}
                        onClick={() => inputRef.current?.focus()}
                    />
                    <button className="diag-employee-clear" onClick={clearSelection} title="Limpar seleção" type="button">
                        <X size={12} />
                    </button>
                </>
            ) : (
                <>
                    <input
                        ref={inputRef}
                        type="text"
                        placeholder="Pesquisar por nome do funcionário..."
                        value={query}
                        onChange={e => setQuery(e.target.value)}
                        onFocus={() => { if (options.length > 0) setShowDropdown(true); }}
                        onKeyDown={handleKeyDown}
                        autoComplete="off"
                    />
                    {searching && (
                        <span className="diag-employee-clear" style={{ background: 'transparent', cursor: 'default' }}>
                            <Loader2 size={12} />
                        </span>
                    )}
                </>
            )}
            {showDropdown && !value && (
                <div className="diag-employee-dropdown">
                    {searching ? (
                        <div className="diag-employee-loading">
                            <Loader2 size={14} /> A pesquisar...
                        </div>
                    ) : options.length === 0 ? (
                        <div className="diag-employee-no-results">
                            Nenhum funcionário encontrado.
                        </div>
                    ) : (
                        options.map((emp, i) => (
                            <div
                                key={emp.id}
                                className={`diag-employee-option ${i === activeIndex ? 'active' : ''}`}
                                onMouseDown={() => selectEmployee(emp)}
                                onMouseEnter={() => setActiveIndex(i)}
                            >
                                <span className="emp-name">{emp.fullName}</span>
                                <span className="emp-meta">
                                    {emp.innuxDepartmentName && <span>{emp.innuxDepartmentName}</span>}
                                    <span className="emp-id">ID #{emp.innuxEmployeeId}</span>
                                </span>
                            </div>
                        ))
                    )}
                </div>
            )}
        </div>
    );
}

// ─── Column Header with Tooltip ───

function ThWithTooltip({ label, tooltip }: { label: string; tooltip: string }) {
    return (
        <th>
            <span className="diag-th-label">
                {label}
                <ModernTooltip content={tooltip} side="bottom">
                    <span className="diag-th-info"><Info size={12} /></span>
                </ModernTooltip>
            </span>
        </th>
    );
}

// ─── Severity Legend ───

function SeverityLegend() {
    return (
        <div className="diag-severity-legend">
            <span className="diag-severity-legend-title">Legenda:</span>
            <span className="diag-legend-item">
                <span className="diag-severity diag-severity--high">Alta</span>
                <span className="diag-legend-desc">Revisar com prioridade</span>
            </span>
            <span className="diag-legend-item">
                <span className="diag-severity diag-severity--medium">Média</span>
                <span className="diag-legend-desc">Divergência relevante</span>
            </span>
            <span className="diag-legend-item">
                <span className="diag-severity diag-severity--low">Baixa</span>
                <span className="diag-legend-desc">Informação limitada ou diferença menor</span>
            </span>
            <span className="diag-legend-item">
                <span className="diag-severity diag-severity--none">Nenhuma</span>
                <span className="diag-legend-desc">Sem divergência relevante</span>
            </span>
        </div>
    );
}

// ─── Help Drawer ───

function DiagnosticsHelpDrawer({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
    return (
        <>
            <div className={`diag-help-overlay ${isOpen ? 'open' : ''}`} onClick={onClose} />
            <div className={`diag-help-drawer ${isOpen ? 'open' : ''}`}>
                <div className="diag-help-header">
                    <button className="diag-help-close" onClick={onClose} aria-label="Fechar">
                        <X size={18} />
                    </button>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                        <div style={{ background: '#fff', color: 'var(--color-primary)', padding: 10, borderRadius: 'var(--radius-sm)' }}>
                            <BookOpen size={22} strokeWidth={2.5} />
                        </div>
                        <div>
                            <h2>Como usar esta tela</h2>
                            <p>Guia Rápido • Revisão de Presenças</p>
                        </div>
                    </div>
                </div>

                <div className="diag-help-body">
                    {/* What is this page */}
                    <section>
                        <div className="diag-help-section-title">
                            <Info size={16} /> O que é esta tela?
                        </div>
                        <p className="diag-help-text">
                            Esta tela compara o resultado processado pelo Innux com uma interpretação
                            feita pelo Portal a partir das picagens brutas. Ela é apenas diagnóstica
                            e não altera informações no Innux ou Primavera.
                        </p>
                    </section>

                    {/* How to use */}
                    <section>
                        <div className="diag-help-section-title">
                            <Search size={16} /> Como utilizar
                        </div>
                        <ol className="diag-help-steps">
                            {[
                                'Selecione um período (data inicial e final).',
                                'Opcionalmente, pesquise um funcionário pelo nome.',
                                'Escolha se deseja ver apenas divergências.',
                                'Clique em "Pesquisar".',
                                'Analise os cartões de resumo no topo.',
                                'Clique no ícone de olho (👁) na coluna Ação para inspecionar um caso em detalhe.'
                            ].map((step, i) => (
                                <li key={i}>
                                    <span className="diag-help-step-num">{i + 1}</span>
                                    <span>{step}</span>
                                </li>
                            ))}
                        </ol>
                    </section>

                    {/* Field glossary */}
                    <section>
                        <div className="diag-help-section-title">
                            <FileSearch size={16} /> Campos da tabela
                        </div>
                        <table className="diag-help-field-table">
                            <thead>
                                <tr><th>Campo</th><th>Descrição</th></tr>
                            </thead>
                            <tbody>
                                <tr><td>Status Innux</td><td>Resultado da presença conforme processado pelo sistema Innux.</td></tr>
                                <tr><td>Status Portal</td><td>Resultado calculado pelo Portal a partir das picagens brutas do terminal.</td></tr>
                                <tr><td>Severidade</td><td>Grau de importância da diferença entre Innux e Portal.</td></tr>
                                <tr><td>Confiança</td><td>Qualidade da interpretação do Portal (depende da clareza das picagens).</td></tr>
                                <tr><td>Min. Innux</td><td>Minutos trabalhados disponíveis no Innux, quando existem.</td></tr>
                                <tr><td>Min. Portal</td><td>Minutos trabalhados calculados pelo Portal a partir das picagens brutas.</td></tr>
                                <tr><td>Ação</td><td>Abre o painel lateral com detalhes completos do caso.</td></tr>
                            </tbody>
                        </table>
                    </section>

                    {/* Severity explanation */}
                    <section>
                        <div className="diag-help-section-title">
                            <AlertTriangle size={16} /> Níveis de severidade
                        </div>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                                <span className="diag-severity diag-severity--high">Alta</span>
                                <span className="diag-help-text">Divergência crítica — Innux e Portal discordam sobre presença/ausência.</span>
                            </div>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                                <span className="diag-severity diag-severity--medium">Média</span>
                                <span className="diag-help-text">Diferença relevante em horários ou minutos trabalhados.</span>
                            </div>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                                <span className="diag-severity diag-severity--low">Baixa</span>
                                <span className="diag-help-text">Informação limitada ou diferença menor (ex: dados incompletos).</span>
                            </div>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                                <span className="diag-severity diag-severity--none">Nenhuma</span>
                                <span className="diag-help-text">Innux e Portal concordam — sem divergência relevante.</span>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="diag-help-footer">
                    <button onClick={onClose}>Entendido</button>
                </div>
            </div>
        </>
    );
}

// ─── Main Content ───

function DiagnosticsContent() {
    // Filters
    const [startDate, setStartDate] = useState(defaultStartDate());
    const [endDate, setEndDate] = useState(toIsoDate(new Date()));
    const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
    const [severityFilter, setSeverityFilter] = useState('all');
    const [onlyDiscrepancies, setOnlyDiscrepancies] = useState(false);

    // State
    const [data, setData] = useState<RangeResult | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [validationError, setValidationError] = useState<string | null>(null);
    const [hasSearched, setHasSearched] = useState(false);
    const [showHelp, setShowHelp] = useState(false);

    // Drawer
    const [drawerRow, setDrawerRow] = useState<ComparisonResult | null>(null);
    const [punchDetail, setPunchDetail] = useState<PunchInterpretation | null>(null);
    const [punchLoading, setPunchLoading] = useState(false);

    const handleSearch = useCallback(async () => {
        setValidationError(null);
        setError(null);

        if (!startDate || !endDate) {
            setValidationError('Data inicial e data final são obrigatórias.');
            return;
        }
        if (daysBetween(startDate, endDate) > 31) {
            setValidationError('O intervalo máximo permitido é 31 dias.');
            return;
        }
        if (new Date(startDate) > new Date(endDate)) {
            setValidationError('A data inicial deve ser anterior à data final.');
            return;
        }

        setLoading(true);
        setHasSearched(true);
        try {
            const params: any = { startDate, endDate, onlyDiscrepancies };
            if (selectedEmployee) params.innuxEmployeeId = selectedEmployee.innuxEmployeeId;
            const result = await api.hrAttendanceDiagnostics.compareRange(params);
            setData(result);
        } catch (err: any) {
            setError(err?.message || 'Erro desconhecido ao carregar dados diagnósticos.');
        } finally {
            setLoading(false);
        }
    }, [startDate, endDate, selectedEmployee, onlyDiscrepancies]);

    // Open drawer
    const openDrawer = useCallback(async (row: ComparisonResult) => {
        setDrawerRow(row);
        setPunchDetail(null);
        setPunchLoading(true);
        try {
            const dateStr = new Date(row.date).toISOString().split('T')[0];
            const result = await api.hrAttendanceDiagnostics.interpretPunches(row.innuxEmployeeId, dateStr);
            setPunchDetail(result);
        } catch {
            setPunchDetail(null);
        } finally {
            setPunchLoading(false);
        }
    }, []);

    const closeDrawer = useCallback(() => {
        setDrawerRow(null);
        setPunchDetail(null);
    }, []);

    // Close drawer on Escape
    useEffect(() => {
        const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') closeDrawer(); };
        window.addEventListener('keydown', handler);
        return () => window.removeEventListener('keydown', handler);
    }, [closeDrawer]);

    // Client-side severity filter
    const filteredResults = data?.results?.filter(r => {
        if (severityFilter === 'all') return true;
        return r.discrepancySeverity === severityFilter;
    }) ?? [];

    // Summary KPIs
    const noneCount = data ? data.totalEmployeeDays - data.discrepancyCount : 0;

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
            {/* Banner + Help trigger */}
            <div className="diag-banner">
                <ShieldCheck size={20} />
                <span>Esta tela é apenas diagnóstica. Nenhuma informação é gravada no Innux ou Primavera.</span>
                <button className="diag-help-trigger" onClick={() => setShowHelp(true)} type="button">
                    <HelpCircle size={14} /> Como usar esta tela?
                </button>
            </div>

            {/* Help Drawer */}
            <DiagnosticsHelpDrawer isOpen={showHelp} onClose={() => setShowHelp(false)} />

            {/* Filters */}
            <div className="diag-filter-bar">
                <div className="diag-filter-group">
                    <label htmlFor="diag-start">Data Inicial</label>
                    <input id="diag-start" type="date" value={startDate} onChange={e => setStartDate(e.target.value)} />
                </div>
                <div className="diag-filter-group">
                    <label htmlFor="diag-end">Data Final</label>
                    <input id="diag-end" type="date" value={endDate} onChange={e => setEndDate(e.target.value)} />
                </div>
                <div className="diag-filter-group">
                    <label>Funcionário</label>
                    <EmployeeAutocomplete value={selectedEmployee} onChange={setSelectedEmployee} />
                </div>
                <div className="diag-filter-group">
                    <label htmlFor="diag-sev">Severidade</label>
                    <select id="diag-sev" value={severityFilter} onChange={e => setSeverityFilter(e.target.value)}>
                        <option value="all">Todos</option>
                        <option value="High">Alta</option>
                        <option value="Medium">Média</option>
                        <option value="Low">Baixa</option>
                        <option value="None">Nenhuma</option>
                    </select>
                </div>
                <label className="diag-filter-toggle">
                    <input type="checkbox" checked={onlyDiscrepancies} onChange={e => setOnlyDiscrepancies(e.target.checked)} />
                    Apenas divergências
                </label>
                <button className="diag-btn-search" onClick={handleSearch} disabled={loading}>
                    {loading ? <Loader2 size={16} /> : <Search size={16} />}
                    Pesquisar
                </button>
                {validationError && (
                    <div className="diag-validation-error">
                        <AlertTriangle size={16} />
                        {validationError}
                    </div>
                )}
            </div>

            {/* Error */}
            {error && (
                <div className="diag-error-box">
                    <AlertCircle size={18} />
                    <div>{error}</div>
                </div>
            )}

            {/* Loading */}
            {loading && (
                <div className="diag-loading">
                    <Loader2 size={24} />
                    A carregar dados diagnósticos...
                </div>
            )}

            {/* Results */}
            {!loading && data && (
                <>
                    {/* Summary KPIs */}
                    <div className="diag-summary-grid">
                        <KPICard title="Total Dias" value={data.totalEmployeeDays} icon={<FileSearch size={20} />} color="var(--color-primary)" />
                        <KPICard title="Sem Divergência" value={noneCount} icon={<CheckCircle2 size={20} />} color="#6b7280" />
                        <KPICard title="Baixa" value={data.lowSeverityCount} icon={<Info size={20} />} color="#2563eb" />
                        <KPICard title="Média" value={data.mediumSeverityCount} icon={<AlertTriangle size={20} />} color="#ea580c" />
                        <KPICard title="Alta" value={data.highSeverityCount} icon={<AlertCircle size={20} />} color="#dc2626" />
                        <KPICard title="Tempo (ms)" value={data.executionTimeMs} icon={<Clock size={20} />} color="var(--color-text-muted)" />
                    </div>

                    {/* Severity Legend */}
                    <SeverityLegend />

                    {/* Table */}
                    {filteredResults.length === 0 ? (
                        <div className="diag-empty">
                            <FileSearch size={48} />
                            <p>{onlyDiscrepancies
                                ? 'Nenhuma divergência encontrada no período selecionado.'
                                : 'Nenhum registro encontrado para os filtros selecionados.'}</p>
                        </div>
                    ) : (
                        <div className="diag-table-container">
                            <table className="diag-table">
                                <thead>
                                    <tr>
                                        <th>Data</th>
                                        <th>Funcionário</th>
                                        <ThWithTooltip label="Status Innux" tooltip="Resultado da presença conforme processado pelo Innux." />
                                        <ThWithTooltip label="Status Portal" tooltip="Resultado calculado pelo Portal a partir das picagens brutas." />
                                        <ThWithTooltip label="Severidade" tooltip="Grau de importância da diferença entre Innux e Portal." />
                                        <th>Ent. Innux</th>
                                        <th>Ent. Portal</th>
                                        <th>Saída Innux</th>
                                        <th>Saída Portal</th>
                                        <ThWithTooltip label="Min. Innux" tooltip="Minutos trabalhados disponíveis no Innux, quando existem." />
                                        <ThWithTooltip label="Min. Portal" tooltip="Minutos trabalhados calculados pelo Portal a partir das picagens." />
                                        <ThWithTooltip label="Confiança" tooltip="Qualidade da interpretação do Portal (depende da clareza das picagens)." />
                                        <th>Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {filteredResults.map((r, i) => (
                                        <tr key={`${r.innuxEmployeeId}-${r.date}-${i}`} onClick={() => openDrawer(r)}>
                                            <td className="td-mono">{formatDate(r.date)}</td>
                                            <td title={`ID: ${r.innuxEmployeeId}`}>
                                                {r.employeeName || `#${r.innuxEmployeeId}`}
                                            </td>
                                            <td>{statusLabel(r.innuxStatus)}</td>
                                            <td>{statusLabel(r.portalStatus)}</td>
                                            <td>
                                                <span className={`diag-severity ${severityClass(r.discrepancySeverity)}`}>
                                                    {severityLabel(r.discrepancySeverity)}
                                                </span>
                                            </td>
                                            <td className="td-mono">{r.innuxFirstEntry || '—'}</td>
                                            <td className="td-mono">{r.portalFirstEntry || '—'}</td>
                                            <td className="td-mono">{r.innuxLastExit || '—'}</td>
                                            <td className="td-mono">{r.portalLastExit || '—'}</td>
                                            <td className="td-mono">{r.innuxWorkedMinutes}</td>
                                            <td className="td-mono">{r.portalWorkedMinutes}</td>
                                            <td>
                                                <span className={`diag-confidence ${confidenceClass(r.confidenceLevel)}`}>
                                                    {confidenceLabel(r.confidenceLevel)}
                                                </span>
                                            </td>
                                            <td>
                                                <Eye size={16} style={{ color: 'var(--color-primary)', cursor: 'pointer' }} />
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </>
            )}

            {/* Empty state before first search */}
            {!loading && !data && hasSearched === false && (
                <div className="diag-initial-guidance">
                    <div className="diag-initial-guidance-icon">
                        <ShieldCheck size={28} />
                    </div>
                    <p>
                        Comece selecionando um período e, se desejar, um funcionário.
                        Depois clique em <strong>Pesquisar</strong>.
                    </p>
                    <p>
                        Para analisar um caso, clique no ícone de olho na coluna <strong>Ação</strong>.
                    </p>
                    <span className="diag-guidance-hint">
                        <HelpCircle size={13} style={{ verticalAlign: 'middle', marginRight: 4 }} />
                        Dúvidas? Clique em "Como usar esta tela?" no topo.
                    </span>
                </div>
            )}

            {/* Detail Drawer */}
            <div className={`diag-drawer-overlay ${drawerRow ? 'open' : ''}`} onClick={closeDrawer} />
            <div className={`diag-drawer ${drawerRow ? 'open' : ''}`}>
                {drawerRow && (
                    <>
                        <div className="diag-drawer-header">
                            <h3>
                                {drawerRow.employeeName || `#${drawerRow.innuxEmployeeId}`} — {formatDate(drawerRow.date)}
                            </h3>
                            <button className="diag-drawer-close" onClick={closeDrawer} aria-label="Fechar">
                                <X size={18} />
                            </button>
                        </div>
                        <div className="diag-drawer-body">
                            {/* Severity Badge */}
                            <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                                <span className={`diag-severity ${severityClass(drawerRow.discrepancySeverity)}`}>
                                    {severityLabel(drawerRow.discrepancySeverity)}
                                </span>
                                <span className={`diag-confidence ${confidenceClass(drawerRow.confidenceLevel)}`}>
                                    <CircleDot size={12} /> Confiança: {confidenceLabel(drawerRow.confidenceLevel)}
                                </span>
                            </div>

                            {/* Innux Side */}
                            <div className="diag-section">
                                <div className="diag-section-title">Innux (Processado)</div>
                                <div className="diag-kv-row"><span className="label">Status</span><span className="value">{statusLabel(drawerRow.innuxStatus)}</span></div>
                                <div className="diag-kv-row"><span className="label">Entrada</span><span className="value">{drawerRow.innuxFirstEntry || '—'}</span></div>
                                <div className="diag-kv-row"><span className="label">Saída</span><span className="value">{drawerRow.innuxLastExit || '—'}</span></div>
                                <div className="diag-kv-row"><span className="label">Min. Trabalhados</span><span className="value">{drawerRow.innuxWorkedMinutes}</span></div>
                                <div className="diag-kv-row"><span className="label">Min. Esperados</span><span className="value">{drawerRow.innuxExpectedMinutes}</span></div>
                                <div className="diag-kv-row"><span className="label">Fonte Min. Trab.</span><span className="value">{drawerRow.innuxWorkedMinutesSource}</span></div>
                                {drawerRow.innuxWorkedMinutesEnriched && (
                                    <div className="diag-kv-row"><span className="label">Enriquecido</span><span className="value" style={{ color: '#16a34a' }}>Sim (AlteracoesPeriodos)</span></div>
                                )}
                            </div>

                            {/* Portal Side */}
                            <div className="diag-section">
                                <div className="diag-section-title">Portal (Interpretação)</div>
                                <div className="diag-kv-row"><span className="label">Status</span><span className="value">{statusLabel(drawerRow.portalStatus)}</span></div>
                                <div className="diag-kv-row"><span className="label">Entrada</span><span className="value">{drawerRow.portalFirstEntry || '—'}</span></div>
                                <div className="diag-kv-row"><span className="label">Saída</span><span className="value">{drawerRow.portalLastExit || '—'}</span></div>
                                <div className="diag-kv-row"><span className="label">Min. Trabalhados</span><span className="value">{drawerRow.portalWorkedMinutes}</span></div>
                                <div className="diag-kv-row"><span className="label">Min. Esperados</span><span className="value">{drawerRow.portalExpectedMinutes}</span></div>
                                <div className="diag-kv-row"><span className="label">Resolução Escala</span><span className="value">{drawerRow.scheduleResolutionSource}</span></div>
                            </div>

                            {/* Discrepancy Messages */}
                            {drawerRow.discrepancyMessages.length > 0 && (
                                <div className="diag-section">
                                    <div className="diag-section-title">Divergências</div>
                                    <ul className="diag-messages">
                                        {drawerRow.discrepancyMessages.map((m, i) => (
                                            <li key={i} className={msgClass(drawerRow.discrepancySeverity)}>{m}</li>
                                        ))}
                                    </ul>
                                </div>
                            )}

                            {/* Portal Warnings */}
                            {drawerRow.portalWarnings.length > 0 && (
                                <div className="diag-section">
                                    <div className="diag-section-title">Avisos Portal</div>
                                    <ul className="diag-messages">
                                        {drawerRow.portalWarnings.map((w, i) => (
                                            <li key={i} className="msg-info">{w}</li>
                                        ))}
                                    </ul>
                                </div>
                            )}

                            {/* Recommended Action */}
                            <div className="diag-section">
                                <div className="diag-section-title">Ação Recomendada</div>
                                <p style={{ fontSize: '0.85rem', margin: 0, color: 'var(--color-text-main)', lineHeight: 1.5 }}>
                                    {drawerRow.recommendedReviewAction}
                                </p>
                            </div>

                            {/* Punch Detail (loaded on demand) */}
                            {punchLoading && (
                                <div className="diag-loading" style={{ padding: '30px 0' }}>
                                    <Loader2 size={18} /> A carregar picagens...
                                </div>
                            )}

                            {punchDetail && (
                                <>
                                    {/* Raw Punches */}
                                    <div className="diag-section">
                                        <div className="diag-section-title">
                                            Picagens Brutas ({punchDetail.rawPunches.length})
                                        </div>
                                        {punchDetail.rawPunches.length === 0 ? (
                                            <p style={{ fontSize: '0.8rem', color: 'var(--color-text-muted)', margin: 0 }}>
                                                Nenhuma picagem encontrada.
                                            </p>
                                        ) : (
                                            <div className="diag-punch-list">
                                                {punchDetail.rawPunches.map((p, i) => {
                                                    const dirClass = p.interpretedDirection === 'Entry' ? 'diag-punch-item--entry'
                                                        : p.interpretedDirection === 'Exit' ? 'diag-punch-item--exit'
                                                        : 'diag-punch-item--unknown';
                                                    return (
                                                        <div key={i} className={`diag-punch-item ${dirClass} ${p.isDuplicateCandidate ? 'diag-punch-item--duplicate' : ''}`}
                                                            title={p.interpretationReason}>
                                                            <span className="diag-punch-time">{p.punchTimeFormatted}</span>
                                                            <span className="diag-punch-dir">{p.directionLabel}</span>
                                                            <span style={{ fontSize: '0.72rem', color: 'var(--color-text-muted)' }}>
                                                                {p.interpretationRule}
                                                            </span>
                                                            {p.terminalName && (
                                                                <span style={{ fontSize: '0.7rem', color: 'var(--color-text-muted)', marginLeft: 'auto' }}>
                                                                    {p.terminalName}
                                                                </span>
                                                            )}
                                                        </div>
                                                    );
                                                })}
                                            </div>
                                        )}
                                    </div>

                                    {/* Punch Pairs */}
                                    {punchDetail.punchPairs.length > 0 && (
                                        <div className="diag-section">
                                            <div className="diag-section-title">
                                                Pares de Picagem ({punchDetail.punchPairs.length})
                                            </div>
                                            {punchDetail.punchPairs.map((pair, i) => (
                                                <div key={i} className={`diag-pair-card ${pair.pairType !== 'Complete' ? 'diag-pair-card--incomplete' : ''}`}>
                                                    <span className="diag-punch-time" style={{ color: '#16a34a' }}>
                                                        {pair.entry?.punchTimeFormatted || '??:??'}
                                                    </span>
                                                    <ChevronRight size={14} className="pair-arrow" />
                                                    <span className="diag-punch-time" style={{ color: '#dc2626' }}>
                                                        {pair.exit?.punchTimeFormatted || '??:??'}
                                                    </span>
                                                    <span className="pair-minutes">{pair.workedMinutes} min</span>
                                                </div>
                                            ))}
                                        </div>
                                    )}

                                    {/* Applied Rules */}
                                    {punchDetail.appliedRules.length > 0 && (
                                        <div className="diag-section">
                                            <div className="diag-section-title">Regras Aplicadas</div>
                                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                                                {punchDetail.appliedRules.map((rule, i) => (
                                                    <span key={i} style={{
                                                        fontSize: '0.7rem', fontWeight: 600, padding: '3px 8px',
                                                        background: 'rgba(0, 77, 144, 0.06)', color: 'var(--color-primary)',
                                                        borderRadius: 'var(--radius-full)', border: '1px solid rgba(0, 77, 144, 0.12)'
                                                    }}>
                                                        {rule}
                                                    </span>
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </>
                            )}
                        </div>
                    </>
                )}
            </div>
        </div>
    );
}
