// <auto-generated />
using System;
using AlplaPortal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlplaPortal.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324160642_AddDocumentExtractionSettings")]
    partial class AddDocumentExtractionSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlplaPortal.Domain.Entities.CapexOpexClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CapexOpexClassifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "CAPEX"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "OPEX"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "AlplaPLASTICO"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "AlplaSOPRO"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CostCenters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CC-LOG-01",
                            IsActive = true,
                            Name = "CC-LOG-01"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CC-ADM-01",
                            IsActive = true,
                            Name = "CC-ADM-01"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AOA",
                            IsActive = true,
                            Symbol = "Kz"
                        },
                        new
                        {
                            Id = 2,
                            Code = "USD",
                            IsActive = true,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EUR",
                            IsActive = true,
                            Symbol = "€"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADM",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FIN",
                            IsActive = true,
                            Name = "Financeiro"
                        },
                        new
                        {
                            Id = 3,
                            Code = "LOG",
                            IsActive = true,
                            Name = "Logística"
                        },
                        new
                        {
                            Id = 4,
                            Code = "TI",
                            IsActive = true,
                            Name = "TI"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.DocumentExtractionSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AzureDocumentIntelligenceEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("AzureDocumentIntelligenceTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("DefaultProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GlobalTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<bool?>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LocalOcrBaseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("LocalOcrEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("LocalOcrTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<bool?>("OpenAiEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("OpenAiTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DocumentExtractionSettings");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.IvaRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RatePercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("IvaRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "IVA_14",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "IVA 14%",
                            RatePercent = 14.0m
                        },
                        new
                        {
                            Id = 2,
                            Code = "IVA_7",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "IVA 7%",
                            RatePercent = 7.0m
                        },
                        new
                        {
                            Id = 3,
                            Code = "IVA_5",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "IVA 5%",
                            RatePercent = 5.0m
                        },
                        new
                        {
                            Id = 4,
                            Code = "IVA_3",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "IVA 3%",
                            RatePercent = 3.0m
                        },
                        new
                        {
                            Id = 5,
                            Code = "IVA_0",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Isento (0%)",
                            RatePercent = 0.0m
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.LineItemStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LineItemStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColor = "blue",
                            Code = "WAITING_QUOTATION",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Aguardando Cotação"
                        },
                        new
                        {
                            Id = 2,
                            BadgeColor = "yellow",
                            Code = "PENDING",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Pendente"
                        },
                        new
                        {
                            Id = 3,
                            BadgeColor = "indigo",
                            Code = "UNDER_REVIEW",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Em Análise"
                        },
                        new
                        {
                            Id = 8,
                            BadgeColor = "slate",
                            Code = "WAITING_ORDER",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Aguardando Encomenda"
                        },
                        new
                        {
                            Id = 4,
                            BadgeColor = "cyan",
                            Code = "ORDERED",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Encomendado"
                        },
                        new
                        {
                            Id = 5,
                            BadgeColor = "orange",
                            Code = "PARTIALLY_RECEIVED",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Recebido Parcial"
                        },
                        new
                        {
                            Id = 6,
                            BadgeColor = "green",
                            Code = "RECEIVED",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Recebido"
                        },
                        new
                        {
                            Id = 7,
                            BadgeColor = "red",
                            Code = "CANCELLED",
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Cancelado"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.NeedLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NeedLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BAIXO",
                            IsActive = true,
                            Name = "Baixo"
                        },
                        new
                        {
                            Id = 2,
                            Code = "NORMAL",
                            IsActive = true,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 3,
                            Code = "URGENTE",
                            IsActive = true,
                            Name = "Urgente"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CRITICO",
                            IsActive = true,
                            Name = "Crítico"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "V1",
                            CompanyId = 1,
                            IsActive = true,
                            Name = "Viana 1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "V2",
                            CompanyId = 1,
                            IsActive = true,
                            Name = "Viana 2"
                        },
                        new
                        {
                            Id = 3,
                            Code = "V3",
                            CompanyId = 2,
                            IsActive = true,
                            Name = "Viana 3"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ProformaAttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIvaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTaxableBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProformaAttachmentId");

                    b.HasIndex("RequestId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.QuotationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DivergenceNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossSubtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IvaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IvaRateId")
                        .HasColumnType("int");

                    b.Property<decimal>("IvaRatePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LineItemStatusId")
                        .HasColumnType("int");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IvaRateId");

                    b.HasIndex("LineItemStatusId");

                    b.HasIndex("QuotationId");

                    b.HasIndex("UnitId");

                    b.ToTable("QuotationItems");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlplaProdReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AreaApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CapexOpexClassificationId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentResponsibleRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrentResponsibleUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedTotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("FinalApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NeedByDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NeedLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("PrimaveraReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SelectedQuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AreaApproverId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CapexOpexClassificationId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FinalApproverId");

                    b.HasIndex("NeedLevelId");

                    b.HasIndex("PlantId");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasFilter("[RequestNumber] IS NOT NULL");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.RequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("FileSizeMBytes")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("RequestAttachments");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.RequestLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivergenceNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemPriority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineItemStatusId")
                        .HasColumnType("int");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("LineItemStatusId");

                    b.HasIndex("PlantId");

                    b.HasIndex("RequestId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UnitId");

                    b.ToTable("RequestLineItems");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColor = "gray",
                            Code = "DRAFT",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Rascunho"
                        },
                        new
                        {
                            Id = 19,
                            BadgeColor = "cyan",
                            Code = "SUBMITTED",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Submetido"
                        },
                        new
                        {
                            Id = 2,
                            BadgeColor = "blue",
                            Code = "WAITING_QUOTATION",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Aguardando Cotação"
                        },
                        new
                        {
                            Id = 3,
                            BadgeColor = "indigo",
                            Code = "WAITING_AREA_APPROVAL",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Aguardando Aprovação da Área"
                        },
                        new
                        {
                            Id = 4,
                            BadgeColor = "orange",
                            Code = "AREA_ADJUSTMENT",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Reajuste A.A"
                        },
                        new
                        {
                            Id = 5,
                            BadgeColor = "purple",
                            Code = "WAITING_FINAL_APPROVAL",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Aguardando Aprovação Final"
                        },
                        new
                        {
                            Id = 6,
                            BadgeColor = "teal",
                            Code = "FINAL_ADJUSTMENT",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Reajuste A.F"
                        },
                        new
                        {
                            Id = 7,
                            BadgeColor = "red",
                            Code = "REJECTED",
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Rejeitado"
                        },
                        new
                        {
                            Id = 8,
                            BadgeColor = "yellow",
                            Code = "WAITING_COST_CENTER",
                            DisplayOrder = 9,
                            IsActive = true,
                            Name = "Inserir C.C"
                        },
                        new
                        {
                            Id = 9,
                            BadgeColor = "green",
                            Code = "APPROVED",
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Aprovado"
                        },
                        new
                        {
                            Id = 10,
                            BadgeColor = "slate",
                            Code = "PROFORMA_INVOICE_INSERTED",
                            DisplayOrder = 11,
                            IsActive = true,
                            Name = "Fatura Proforma Inserida"
                        },
                        new
                        {
                            Id = 11,
                            BadgeColor = "cyan",
                            Code = "PO_REQUESTED",
                            DisplayOrder = 12,
                            IsActive = true,
                            Name = "Solicitado P.O"
                        },
                        new
                        {
                            Id = 12,
                            BadgeColor = "sky",
                            Code = "PO_ISSUED",
                            DisplayOrder = 13,
                            IsActive = true,
                            Name = "P.O Emitida"
                        },
                        new
                        {
                            Id = 13,
                            BadgeColor = "rose",
                            Code = "PAYMENT_REQUEST_SENT",
                            DisplayOrder = 14,
                            IsActive = true,
                            Name = "Solicitação Pagamento Enviada"
                        },
                        new
                        {
                            Id = 14,
                            BadgeColor = "violet",
                            Code = "PAYMENT_SCHEDULED",
                            DisplayOrder = 15,
                            IsActive = true,
                            Name = "Pagamento Agendado"
                        },
                        new
                        {
                            Id = 15,
                            BadgeColor = "fuchsia",
                            Code = "PAYMENT_COMPLETED",
                            DisplayOrder = 16,
                            IsActive = true,
                            Name = "Pagamento Realizado"
                        },
                        new
                        {
                            Id = 16,
                            BadgeColor = "stone",
                            Code = "WAITING_RECEIPT",
                            DisplayOrder = 17,
                            IsActive = true,
                            Name = "Aguardando Recibo"
                        },
                        new
                        {
                            Id = 21,
                            BadgeColor = "indigo",
                            Code = "IN_FOLLOWUP",
                            DisplayOrder = 18,
                            IsActive = true,
                            Name = "Em Acompanhamento"
                        },
                        new
                        {
                            Id = 17,
                            BadgeColor = "emerald",
                            Code = "COMPLETED",
                            DisplayOrder = 19,
                            IsActive = true,
                            Name = "Finalizado"
                        },
                        new
                        {
                            Id = 18,
                            BadgeColor = "amber",
                            Code = "CANCELLED",
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "Cancelado"
                        },
                        new
                        {
                            Id = 20,
                            BadgeColor = "emerald",
                            Code = "QUOTATION_COMPLETED",
                            DisplayOrder = 21,
                            IsActive = false,
                            Name = "Cotação Concluída"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.RequestStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("PreviousStatusId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestStatusHistories");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RequestTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "QUOTATION",
                            IsActive = true,
                            Name = "Cotação"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PAYMENT",
                            IsActive = true,
                            Name = "Pagamento"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Solicitante"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Aprovador de Area"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Comprador"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "Financeiro"
                        },
                        new
                        {
                            Id = 5,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PortalCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrimaveraCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PortalCode")
                        .IsUnique()
                        .HasFilter("[PortalCode] IS NOT NULL");

                    b.HasIndex("PrimaveraCode")
                        .IsUnique()
                        .HasFilter("[PrimaveraCode] IS NOT NULL AND [PrimaveraCode] <> ''");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Alpla Global Services",
                            PortalCode = "SUP-000001"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Standard Supplier 01",
                            PortalCode = "SUP-000002"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.SystemCounter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemCounters");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsDecimalQuantity")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowsDecimalQuantity = false,
                            Code = "UN",
                            IsActive = true,
                            Name = "Unidade"
                        },
                        new
                        {
                            Id = 2,
                            AllowsDecimalQuantity = false,
                            Code = "EA",
                            IsActive = true,
                            Name = "Each"
                        },
                        new
                        {
                            Id = 3,
                            AllowsDecimalQuantity = true,
                            Code = "KG",
                            IsActive = true,
                            Name = "Quilograma"
                        },
                        new
                        {
                            Id = 4,
                            AllowsDecimalQuantity = true,
                            Code = "L",
                            IsActive = true,
                            Name = "Litro"
                        },
                        new
                        {
                            Id = 5,
                            AllowsDecimalQuantity = true,
                            Code = "M",
                            IsActive = true,
                            Name = "Metro"
                        },
                        new
                        {
                            Id = 6,
                            AllowsDecimalQuantity = false,
                            Code = "CX",
                            IsActive = true,
                            Name = "Caixa"
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "requester@alpla.com",
                            FullName = "Mock Requester",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "comprador@alpla.com",
                            FullName = "Comprador Especialista",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "diretor@alpla.com",
                            FullName = "Diretor (Aprovador)",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "dev@alpla.com",
                            FullName = "Dev Fallback",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentScopeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("DepartmentScopeId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoleAssignments");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Plant", b =>
                {
                    b.HasOne("AlplaPortal.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Quotation", b =>
                {
                    b.HasOne("AlplaPortal.Domain.Entities.RequestAttachment", "ProformaAttachment")
                        .WithMany()
                        .HasForeignKey("ProformaAttachmentId");

                    b.HasOne("AlplaPortal.Domain.Entities.Request", "Request")
                        .WithMany("Quotations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProformaAttachment");

                    b.Navigation("Request");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.QuotationItem", b =>
                {
                    b.HasOne("AlplaPortal.Domain.Entities.IvaRate", "IvaRate")
                        .WithMany()
                        .HasForeignKey("IvaRateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlplaPortal.Domain.Entities.LineItemStatus", "LineItemStatus")
                        .WithMany()
                        .HasForeignKey("LineItemStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlplaPortal.Domain.Entities.Quotation", "Quotation")
                        .WithMany("Items")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("IvaRate");

                    b.Navigation("LineItemStatus");

                    b.Navigation("Quotation");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Request", b =>
                {
                    b.HasOne("AlplaPortal.Domain.Entities.User", "AreaApprover")
                        .WithMany()
                        .HasForeignKey("AreaApproverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlplaPortal.Domain.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlplaPortal.Domain.Entities.CapexOpexClassification", "CapexOpexClassification")
                        .WithMany()
                        .HasForeignKey("CapexOpexClassificationId");

                    b.HasOne("AlplaPortal.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("AlplaPortal.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.User", "FinalApprover")
                        .WithMany()
                        .HasForeignKey("FinalApproverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlplaPortal.Domain.Entities.NeedLevel", "NeedLevel")
                        .WithMany()
                        .HasForeignKey("NeedLevelId");

                    b.HasOne("AlplaPortal.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId");

                    b.HasOne("AlplaPortal.Domain.Entities.RequestType", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.RequestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("AreaApprover");

                    b.Navigation("Buyer");

                    b.Navigation("CapexOpexClassification");

                    b.Navigation("Company");

                    b.Navigation("Currency");

                    b.Navigation("Department");

                    b.Navigation("FinalApprover");

                    b.Navigation("NeedLevel");

                    b.Navigation("Plant");

                    b.Navigation("RequestType");

                    b.Navigation("Requester");

                    b.Navigation("Status");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.RequestAttachment", b =>
                {
                    b.HasOne("AlplaPortal.Domain.Entities.Request", "Request")
                        .WithMany("Attachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.RequestLineItem", b =>
                {
                    b.HasOne("AlplaPortal.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId");

                    b.HasOne("AlplaPortal.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("AlplaPortal.Domain.Entities.LineItemStatus", "LineItemStatus")
                        .WithMany()
                        .HasForeignKey("LineItemStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlplaPortal.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId");

                    b.HasOne("AlplaPortal.Domain.Entities.Request", "Request")
                        .WithMany("LineItems")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.HasOne("AlplaPortal.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CostCenter");

                    b.Navigation("Currency");

                    b.Navigation("LineItemStatus");

                    b.Navigation("Plant");

                    b.Navigation("Request");

                    b.Navigation("Supplier");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.RequestStatusHistory", b =>
                {
                    b.HasOne("AlplaPortal.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.RequestStatus", "NewStatus")
                        .WithMany()
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.RequestStatus", "PreviousStatus")
                        .WithMany()
                        .HasForeignKey("PreviousStatusId");

                    b.HasOne("AlplaPortal.Domain.Entities.Request", "Request")
                        .WithMany("StatusHistories")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("NewStatus");

                    b.Navigation("PreviousStatus");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.User", b =>
                {
                    b.HasOne("AlplaPortal.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.UserRoleAssignment", b =>
                {
                    b.HasOne("AlplaPortal.Domain.Entities.Department", "DepartmentScope")
                        .WithMany()
                        .HasForeignKey("DepartmentScopeId");

                    b.HasOne("AlplaPortal.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlplaPortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentScope");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Quotation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlplaPortal.Domain.Entities.Request", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("LineItems");

                    b.Navigation("Quotations");

                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
