using System;
using System.IO;
using System.Text.Json;
using AlplaPortal.Application.Models.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace AlplaPortal.Api.Services;

/// <summary>Exposes the running backend's canonical build identity (loaded once at startup).</summary>
public interface IBuildInfoProvider
{
    BuildInfo Current { get; }
}

/// <summary>
/// Loads <c>build-manifest.json</c> (generated by GitHub Actions and deployed beside the API) exactly
/// once, and classifies the result via <see cref="BuildMetadataStatus"/>. This is the single runtime
/// source of version truth — it replaces the stale hard-coded literals in the csproj / diagnostics.
///
/// <para><b>Fail modes:</b> a missing manifest in Development is a clearly-labelled
/// <see cref="BuildMetadataStatus.DevelopmentFallback"/> (never resembling a release); a missing or
/// malformed manifest in TEST/PROD is logged at high severity and surfaced as
/// <see cref="BuildMetadataStatus.Missing"/> / <see cref="BuildMetadataStatus.Malformed"/> so that the
/// deployment-verification gate fails-closed. The API still starts (middleware fails-open on an
/// invalid status) to avoid self-lockout.</para>
/// </summary>
public sealed class BuildInfoProvider : IBuildInfoProvider
{
    private const string ManifestFileName = "build-manifest.json";
    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    public BuildInfo Current { get; }

    public BuildInfoProvider(IHostEnvironment env, ILogger<BuildInfoProvider> logger)
    {
        Current = Load(env, logger);
    }

    private static BuildInfo Load(IHostEnvironment env, ILogger logger)
    {
        var candidates = new[]
        {
            Path.Combine(env.ContentRootPath, ManifestFileName),
            Path.Combine(AppContext.BaseDirectory, ManifestFileName)
        };

        string? path = null;
        foreach (var c in candidates)
        {
            if (File.Exists(c)) { path = c; break; }
        }

        if (path is null)
        {
            if (env.IsDevelopment())
            {
                logger.LogInformation("[BuildInfo] No {File} found — using DevelopmentFallback identity.", ManifestFileName);
                return new BuildInfo
                {
                    Version = "0.0.0-dev",
                    BuildId = "DEV-LOCAL",
                    ShortSha = "dev",
                    Status = BuildMetadataStatus.DevelopmentFallback
                };
            }

            logger.LogError("[BuildInfo] {File} is MISSING in environment '{Env}'. Deployment verification must fail-closed.",
                ManifestFileName, env.EnvironmentName);
            return new BuildInfo { Version = "UNKNOWN", BuildId = "UNKNOWN", ShortSha = "unknown", Status = BuildMetadataStatus.Missing };
        }

        try
        {
            var json = File.ReadAllText(path);
            var parsed = JsonSerializer.Deserialize<BuildInfo>(json, JsonOpts);

            if (parsed is null || string.IsNullOrWhiteSpace(parsed.BuildId) || string.IsNullOrWhiteSpace(parsed.Version)
                || parsed.BuildId == "UNKNOWN")
            {
                logger.LogError("[BuildInfo] {File} at {Path} is MALFORMED (missing version/buildId).", ManifestFileName, path);
                return new BuildInfo { Version = "UNKNOWN", BuildId = "UNKNOWN", ShortSha = "unknown", Status = BuildMetadataStatus.Malformed };
            }

            parsed.Status = BuildMetadataStatus.Valid;
            logger.LogInformation("[BuildInfo] Loaded valid build manifest: version={Version} buildId={BuildId} deploymentId={DeploymentId}",
                parsed.Version, parsed.BuildId, parsed.DeploymentId ?? "(none)");
            return parsed;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "[BuildInfo] Failed to parse {File} at {Path} — treating as MALFORMED.", ManifestFileName, path);
            return new BuildInfo { Version = "UNKNOWN", BuildId = "UNKNOWN", ShortSha = "unknown", Status = BuildMetadataStatus.Malformed };
        }
    }
}
