// ============================================================================
// Frontend build identity (compile-time).
//
// In a GitHub Actions release build, Vite injects VITE_APP_* from the ONE canonical build object
// generated by the workflow (same version + short Git SHA as the backend manifest). Locally, when
// those variables are absent, a clearly-marked DevelopmentFallback identity is used that must NEVER
// resemble a release build.
//
// Compatibility with the backend is decided ONLY by `buildId` equality (see the version monitor and
// the backend enforcement middleware). No secrets are ever placed in VITE_* / public metadata.
// ============================================================================

export type BuildMetadataStatus =
    | 'Valid'
    | 'DevelopmentFallback'
    | 'Missing'
    | 'Malformed'
    | 'Unknown';

const rawVersion = import.meta.env.VITE_APP_VERSION as string | undefined;
const rawBuildId = import.meta.env.VITE_APP_BUILD_ID as string | undefined;
const rawShortSha = import.meta.env.VITE_APP_SHORT_SHA as string | undefined;
const rawBuiltAt = import.meta.env.VITE_APP_BUILT_AT as string | undefined;

// A real release requires at least version + buildId injected at build time.
const isRelease = Boolean(rawBuildId && rawVersion);

export interface FrontendBuildInfo {
    version: string;
    buildId: string;
    shortSha: string;
    builtAtUtc: string;
    status: BuildMetadataStatus;
    /** True only for a genuine GitHub Actions release build. */
    isRelease: boolean;
}

export const buildInfo: FrontendBuildInfo = {
    version: isRelease ? (rawVersion as string) : '0.0.0-dev',
    buildId: isRelease ? (rawBuildId as string) : 'DEV-LOCAL',
    shortSha: isRelease ? (rawShortSha ?? '') : 'dev',
    builtAtUtc: isRelease ? (rawBuiltAt ?? '') : '',
    status: isRelease ? 'Valid' : 'DevelopmentFallback',
    isRelease,
};
